### ISSUE TITLE
コメント機能

### ISSUE THREAD

**Issue by tatsuki-okuda** [tatsuki-okuda/Rails-insta_clone_app#42]
【ゴール】
Ajaxを用いたコメント機能の実装。

```
【必要なもの】
・commentモデルの作成
・commentコントローラの作成
・commentのshow,createのメソッド作成
・axiosでリクエストとレスポンスの作成
・viewでのinputの設置とコメント送信に伴う挙動の作成

```

commentコントローラーのshowwで
初期状態のコメントをjsonで送る。
それをaxiosでリクエストして、レスポンスとしてキャッチして、
表示させる。

createではコメントの新規登録をする。
そして、jsonデータで登録したコメントを返す。
それを既存のコメントと一緒にviewに表示させる。

**Comment by tatsuki-okuda** [comment]
```
【必要なもの】
・commentモデルの作成
・commentコントローラの作成
・commentのshow,createのメソッド作成
・axiosでリクエストとレスポンスの作成
・viewでのinputの設置とコメント送信に伴う挙動の作成
```


## ・commentモデルの作成
## ・commentコントローラの作成

commentはcardに紐づかあせる。
DBでの紐付き
`t.references :card, null: false`

 そして、モデルファイルを紐づかせる。

コメントからみた時に記事は一つだけなので、
1:nの関係値となるので、
`belongs_to :card`
そしてcardでは複数のcommentsを持つので
`has_many :comments, dependent: :destroy`
とする

最後にdbmigrateでデータベースを作成する。

コントローラーも作成する。


## ・viewでのinputの設置とコメント送信に伴う挙動の作成

コメントはカードのコメントのアイコンをクリックした時に
コメントのindexページに飛ぶようにする。

なのでまずはコメントのレーティングを行う。
コメントはindexでその投稿に紐づくコメントの表示と、
コメント入力欄を用意する。

viewのcssも作成する。


## ・commentのshow,createのメソッド作成
## ・axiosでリクエストとレスポンスの作成

1. コメントを作成できるようにする。
2. 作成したコメントを表示させる

この2つを実装する、

### コメントをできるようにする。


まずはjsでtextareaのアイコンクリックで
コメントをpotでレスポンスできるようにする。

コメントのpostのパスに
/cards/:card_id/comments(.:format)
Idが必要なので、まずはそちらを取得する。

urlから取得できるので、
cardの時と同様にデータ属性をコンテンツにつけてjsで取得。

`const cardId = document.querySelector('.comment').dataset.cardId;`

クリックでリクエストをするので、
ボタンアイコンも取得する。

`const commentBtn  = document.querySelector('.comment_input_btn');`

そしてaxiosでpostリクエストを作成する。

```
  commentBtn.addEventListener('click', function(){
    axios.post(`/cards/${cardId}/comments`)
		.then((response) => {
		})
		.catch((e) => {
			console.log(e)
		})
     
  });

```

そしてクリックした時にバリューが空だったら遅れないようにする。


```
 commentBtn.addEventListener('click', function(){
    const commentValue = document.querySelector('.commentValue');
    const value = commentValue.value;
    if(value){
      axios.post(`/cards/${cardId}/comments`)
      .then((response) => {
  
      })
      .catch((e) => {
        console.log(e)
      })
    } else{
      window.alert('コメントを入力してください！');
    }
  });
```

ここで一旦jsがちゃんと動くかを確認する。

→空で送るとちゃんとアラートが出たのでOK


ここまでしたら、
コントローラーでコメントを作成できるようにする。

ストロングパラメータの設置をして、
必要なものだけを保存できるようにする。

 ```
 private
  def comment_params
      params.require(:comment).permit(:content)
  end

```

このストロングパラメータに合わせて,
axiosでリクエストパラメータを作る必要がある。

comment { content: 〜 }

の形でリクエストを送りたいので

```
      axios.post(`/cards/${cardId}/comments`,{
        comment: {content: value}
      }) 


```

とすれば送れそう。

あとはストロングパラメータをcreateで保存できるよにして、
そこからjsonを返す。


  ```
def create
    card = Card.find(params[:card_id])
    @comment = card.comments.build(comment_params)
    @comment.save!
    render json: @comment
  end

```


返ってきたjsonデータから
情報を抜き出して、それをviewのリストに追加する。


```
      .then((response) => {
        const newComment = response.data
        newCommentAdd(newComment);
        commentValue.value = '';
        console.log('ok');
      })

```

```

function newCommentAdd(newComment){
  // ulの取得
  const comentBox = document.querySelector('.comment_box');
  // リストタグを生成
  const listTag = document.createElement("li");
  // leftboxを生成
  const leftBox = document.createElement("div");
  leftBox.classList = "comment_box_leftIcon";
  // roightboxを生成
  const rightBox = document.createElement("div");
  rightBox.classList = "comment_box_rightText";
  // プrpフィールテキスト要素を生成
  const profileText = document.createElement("p");
  profileText.classList = "comment_box_rightText_name";
  // コンテントテキスト要素を生成
  const contentText = document.createElement("p");
  contentText.classList = "comment_box_rightText_text";
  contentText.innerText = escape(newComment.content)
  // rightboxに子要素を加える
  rightBox.appendChild(profileText);
  rightBox.appendChild(contentText);
  // liに子要素を加える
  listTag.appendChild(leftBox);
  listTag.appendChild(rightBox);
  // ulにliを加える
  comentBox.appendChild(listTag);

}

```

これで動くかを確認する。


まずはサーバーログを確認したところ、
postが問題なく遅れていることがわかる。
また、コメントのcreateも確認できている。

https://gist.github.com/tatsuki-okuda/8a6e56164a41cc6d050193096effa639

rails c　でもデータが確認できた。

https://gist.github.com/tatsuki-okuda/49cdddc3ebfd967c8d373086f04b6048

そして、inputの初期化もできているが、
追加されたリストが文字化けしているのでそこを直していきたい。


escapeすると文字化けするので、一旦外しておく。

これで投稿の作成は完了したので次は
アクセスした時に一覧を表示できるようにする。

**Comment by tatsuki-okuda** [comment]
`コメントの一覧をアクセス時に表示させる。`


まずは動機的に処理を作る。

コメントの一覧の表示にはそのコメントをしたユーザーのアバターと名前を表示させたいので、
userモデルと紐づける必要がある。

なので、以下の手順で行う。

```
・userとcommentの紐付け
・commentコントローラからデータを抜き出す。
・viewで表示させる。

```

###・userとcommentの紐付け

まずはマイグレーションファイルでの紐付け。

`t.references :user, null: false`

とする。

次にモデルの紐付け。

ユーザーとコメントはn：1の関係値となる。

1つのコメントから見たらユーザーは常に一人。
ユーザーから見たらコメントは複数ある。

なので、userモデルに
has_many :comments, dependent: :destroy

とcommentモデルに
belongs_to :user
とする。

commentを紐づけた時と関係値が同じことになる。

一応、データベースの変更を加えるので、
dbをrollbackさせてからmigrateさせておく。

https://gist.github.com/tatsuki-okuda/17ae3599fc5d9909e34909b2f805ad0c



ロールバックでコメントが消えたので新くコメントを追加させ流必要があるので、
追加させると、エラーになった。

コメントが保存できないので、原因を探す。

まずはaxiosのログを確認する。

https://gist.github.com/tatsuki-okuda/ded38672a20625d28b2551c92d384012


```
ActiveRecord::RecordInvalid - translation missing: ja.activerecord.errors.messages.record_invalid:
  app/controllers/comments_controller.rb:21:in `create'
```

とある。

翻訳が欠落しているらしい。

エラー分を調べてみると

[translation missing: ja.activerecord.errors.messages.record_invalidエラーの対処](https://qiita.com/anago1030/items/fbfb9c9d581feb19153d)

で翻訳がないから本来のエラー分が表示できないらしい笑
（そういえば翻訳は入れてなかった。。）

なので翻訳を入れる。

app>config>localesにja.ymlを作成して、
日本語訳を入れる。

rails serverを再起動させて、再度コメントを作成してみると、、、、

バリデーションに失敗してた笑
https://gist.github.com/tatsuki-okuda/016f2da4d5e8e9603f1f088e86839f67


ところで、userを入力してくださいとあるが、
今はコメントを投稿したら、ログインしているユーザーの情報を盛り込みたい。
ここではユーザーは入力しないで、コメントしたら
勝手に紐づくようにしたい。。。

と思っていらlikeをした時にuserとcardを紐づけていたが、

 ```
 def create
    card = Card.find(params[:card_id])
    card.likes.create!(user_id: current_user.id)
    # redirect_to request.referer
    render json: { status: 'ok' }
  end

```

createするときにuser_idのカラムを指定して保存している。
とあれば、そこに入る値を指定しないといけないことになる。



今、commentはカードとuserに紐づいているので、
保存するときにcard_idとuser_idを入れる必要がある。
今、card_idからbuildしているがuserの情報が盛り込まれていないために
エラーになっていると言える。

[【Ruby on Rails】コメント機能を作ろう](https://qiita.com/E6YOteYPzmFGfOD/items/ef776d34908872ea19f7)

こちらの記事でcommentに誰がコメントしたかをわかるように
userと紐づけているパターンのものがあるので、参考にできる。

記事では

```
 def create 
    @comment = current_user.comments.build(comment_params)
    @comment.micropost_id = params[:micropost_id]
    if @comment.save
      flash[:success] = 'コメントしました'
      redirect_to @comment.micropost
    else
      @micropost = Micropost.find(params[:micropost_id])  
      @comments = @micropost.comments
      render template: 'microposts/show'
    end

 private

  def comment_params
    params.require(:comment).permit(:content)
  end

```

userに紐づいてbuildをして、さらにポストのidを付与している。
となると今回のケースと同じパターンになるので、こちらでやってみる。

```
 def create
    # card = Card.find(params[:card_id])
    @comment = current_user.comments.build(comment_params)
    @coment.card_id = params[:card_id]

    @comment.save!
    render json: @comment
  end
```

としてコメントを保存できるかやってみる。

結果→
https://gist.github.com/tatsuki-okuda/0f05a9d63462fb7a49c91ad77e6d0d39

エラーログは
```
NoMethodError - undefined method `card_id=' for nil:NilClass:
  app/controllers/comments_controller.rb:21:in `create'
```
に変わったが、nilになっている。

card_idがnilということになる。

一回ここで、binding.pryで処理を止めて
@commentで何が取れるかを確認してみる。


https://gist.github.com/tatsuki-okuda/31363239c53aadb9e1604466bcb81362

buildした時にnilになっているのでそれが原因？

でもエラー分では
`undefined method `
とあるので、そもそも定義の仕方が違う？


```
【整理】
バリテーションでのエラーをどう対処するか

バリテーションでのエラーは
axiosでのパラメータの指定とrailsのストロングパラメータとの違いで起きる。

今はjsでのバリテーションは値が空の時だけなので、
そこは問題なく処理を通過している。（エラーだとアラートができるため）

となると前者。
```


コメントはuserに対してbuildするものとしているので、
エラー分が少し変わっている。

https://gist.github.com/tatsuki-okuda/0fb96aabff6506ec0110c0a17b7274bc

カードを入力しろとあるので、
axiosでカードのIDを含ませて、かつ、ストロングパラメータでもそれを含ませる。


 ```
   axios.post(`/cards/${cardId}/comments`,{
        comment: {content: value, card_id: cardId}
      })
```

```
 def comment_params
      params.require(:comment).permit(:content, :card_id)
  end
```

これでコメントを作成してみる。

問題なくコメントが作成された！！
https://gist.github.com/tatsuki-okuda/0fb96aabff6506ec0110c0a17b7274bc


これで一件落着

【追記1】
rails serverで送られてくるparamsを見ていると、
axiosで指定したパラメータと一緒にcard_idもふづいしている。

`Parameters: {"comment"=>{"content"=>"あ"}, "card_id"=>"7"}`

もしかして、ストロングパラメータで引っかかってたのはこれじゃないかな？
試しにaxiosでのパラメータを戻してみて
`comment: {content: value}`
保存してみたら、うまくいった。。。笑

https://gist.github.com/tatsuki-okuda/2c350ece4513102281b5d68d29819ead

意外と単純なやつだった。


【追記2】
偶然発見したが、コメントを作成するときに
creatメソッドでcard_idを指定の値で入れていたが、
これを設定しなくてもcard_idが勝手に紐づいてくれそう。

axiosでパラメータにcardIdを含ませたらいける。

```
 axios.post(`/cards/${cardId}/comments`,{
        comment: {content: value, card_id: cardId}
      })
```

```
 def create
    @comment = current_user.comments.build(comment_params)
    # @comment.card_id = params[:card_id]
    @comment.save!
    render json: @comment
  end
```
これでコメントを作成してみても問題なく保存できた。
axiosで送るパラメータとしてcard_idを送っているので、
それがbuildした時にcard_idの値として入るということになる。

https://gist.github.com/tatsuki-okuda/2dccca4a8b50853f6acff08253a20dee

あとはデータは紐づいているので、
userの情報を抜き出してviewで表示させればOK!!

一旦、動的にではあるが、
コメントとそのコメントをしたユーザー情報を表示できた。

**Comment by tatsuki-okuda** [comment]
```
【完了】
・動的にアクセスした時にコメントの一覧とそのユーザー情報の表示

【課題】
・アクセスした時の処理をaxiosで実装する
・コメントを作成した時にユーザー情報も非同期で表示させる。（現状コメントだけ表示されているので）
```
https://github.com/tatsuki-okuda/Rails-insta_clone_app/commit/f0c9a52bfd27815c5a0a5f6c01f5ebc9223df39f

[](https://github.com/tatsuki-okuda/Rails-insta_clone_app/commit/f0c9a52bfd27815c5a0a5f6c01f5ebc9223df39f)

**Comment by tatsuki-okuda** [comment]
## ・アクセスした時の処理をaxiosで実装する


axiosで実装するためにはjsonデータで送らないといけない。
なので、jsonでコメントの情報とuserの情報を送らないといけないが、
userの情報はidしかないので、idから名前とアバターのurlを出さないといけない。

railsでjsonを加工してくれるserializerを使う。

その前に、jsonデータをもらうためのルーティングを行う。

idをつけたくないのでcollectionでルーティングをする。

```
resources :comments, only: [:index, :create] do
      collection do
        get :json
      end
    end
```

でjsonメソッドを独自に作って、そこでjsonを発行する。
axiosでもこのメソッドに合わせたリクエストを送る。

`axios.get(`/cards/${cardId}/comments/json`)`


[Active Model Serializerで深くネストした関連を含めたい](https://qiita.com/unasaka/items/08659477c72656df02e8)

activestrageを使ったserializerの使い方の説明がある
[active storage + active model serializerのN + 1問題を解決する](https://qiita.com/Wacci6/items/294f572ea068be318e4d)


[5 ファイルにリンクする](https://railsguides.jp/active_storage_overview.html#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%99%E3%82%8B)


commentのserializerの他に紐付きの関係でuserのserializerを作成して、
そこでusernameとimageを作って、それをcommentで紐づかせるやり方っぽいので、
そちらでやってみる。

先ほど作ったcommentのserializer

```
class CommentSerializer < ActiveModel::Serializer
  attributes :content


  belongs_to :user
end
```



userのserilizerを作成

```
class UserSerializer < ActiveModel::Serializer
  include Rails.application.routes.url_helpers
  attributes :id, :username,:avatar_url


  def avatar_url
    url_for(object.avatar) if object.avataor_image
  end
end

```

モデルで定義したavataor_imageが使えそうだったので、
そちらを入れておく。

これでやると

`Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`


とエラーが出た。
これは記事にもあったとおりなので、
記事の通りに対処する。

config> application.rbに以下を追加。

` routes.default_url_options[:host] = 'http://localhost:3000/' # 追加`

これで一度serverを再起動させると、
エラーなくjsonが出力された！
https://gist.github.com/tatsuki-okuda/6a694491839eb0ab243549dd14a1c7d8

ちゃんとurlもあるので、
これでいけそう。


これでJSを実装してみると

```
function newCommentAdd(newComment){
  // ulの取得
  const commentBox = document.querySelector('.comment_box');
  // リストタグを生成
  const listTag = document.createElement("li");
  // leftboxを生成
  const leftBox = document.createElement("div");
  leftBox.classList = "comment_box_leftIcon";
  // アバター画像
  const avatar = document.createElement("img");
  avatar.setAttribute('src', newComment.user.avatar_url);
  leftBox.appendChild(avatar);
  // roightboxを生成
  const rightBox = document.createElement("div");
  rightBox.classList = "comment_box_rightText";
  // プrpフィールテキスト要素を生成
  const profileText = document.createElement("p");
  profileText.classList = "comment_box_rightText_name";
  profileText.innerText = newComment.user.username
  // コンテントテキスト要素を生成
  const contentText = document.createElement("p");
  contentText.classList = "comment_box_rightText_text";
  contentText.innerText = newComment.content
  // rightboxに子要素を加える
  rightBox.appendChild(profileText);
  rightBox.appendChild(contentText);
  // liに子要素を加える
  listTag.appendChild(leftBox);
  listTag.appendChild(rightBox);
  // ulにliを加える
  commentBox.appendChild(listTag);
}

```


画像がのURLは入っているが表示されなかったので、
おそらく、先ほど設定したURLがおかしいと思われる。
最後につけていたスラッシュをとってみると

` routes.default_url_options[:host] = 'http://localhost:3000' # 追加`

無事に画像も表示されたので、
アクセスした時の一覧表示は完成！！！

次はコメントを作成した時の切り替えだけ！

**Comment by tatsuki-okuda** [comment]
## コメントを作成した時にユーザー情報も非同期で表示させる。（現状コメントだけ表示されているので）

一覧表示させた時と同様にuserを紐づかせたjsonデータを
serializerを使って送ればいいので、

`render json: comment, include: [ :user] `

に変更する。

テストでコメントを作成したら問題なく作成できた！

最後は意外とあっさり解決したが、
serilizerのsactive strageの部分はまだ十分に理解できていないので、
ここに関しては理解を深める。

**Comment by tatsuki-okuda** [comment]
git

[https://github.com/tatsuki-okuda/Rails-insta_clone_app/commit/633d591c21c48a183ca53ddc32896f725c4ab8cd](https://github.com/tatsuki-okuda/Rails-insta_clone_app/commit/633d591c21c48a183ca53ddc32896f725c4ab8cd)
