### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by tatsuki-okuda** [tatsuki-okuda/Rails-insta_clone_app#62]
rspe導入

`gem 'rspec-rails'`
bundleをinstallして

`rails g rspec:install   ` 
を実行でファイルを作る。

## テストの流れ

① 確認したことを決める
② ダミーデータを作成する
③ ダミーデータで1が起こるかを確認する

**Comment by tatsuki-okuda** [comment]
# Cardモデルテスト

rails g rspec:model card
でファイルを作成する、


```
it 'テキストが入力されていたら保存ができる' do
    user = User.create!({
      email: 'test@test.com',
      password: 'password',
      username: 'testtero'
    })
    card = user.card.build({
      content: Faker::Lorem.characters(number: 10)
    })

    expect(card).to be_valid
  end
```

`bundle exec rspec ./spec/models/card_spec.rb`
で実行


```
     NoMethodError:
       undefined method `card' for #<User:0x00007fc2cdfbadf0>
       Did you mean?  cards
     # ./spec/models/card_spec.rb:10:in `block (2 levels) in <top (required)>'
```

とエラーになったのでcardsに変更で再度事項

```
Finished in 0.03653 seconds (files took 1.63 seconds to load)
1 example, 0 failures
```

となったのでテストがちゃんと通っていることがわかる。

**Comment by tatsuki-okuda** [comment]
## rspec

context

前提条件(〜している場合)を定義できる。
その前提条件を定義するために bfeoreを用いる。

```
context '〜な場合'  do
  before do
  end
  it '〜できる' do
  end
end
```

上記で行ったテストだと

```
context 'テキストが入力されていたら' do
    before do
      user = User.create!({
        email: 'test@test.com',
        password: 'password',
        username: 'testtero'
      })
      @card = user.cards.build({
        content: Faker::Lorem.characters(number: 10)
      })
    end
    
    it '保存ができる' do
      expect(@card).to be_valid
    end
  end
```

となる。
スコープを跨ぐ変数の場合は
インスランス変数にすること！



## let

rspecで変数を定義できる。

letを使うときはbeforeを使わないルールになる。


```
 context 'テキストが入力されていたら' do
    let!(:user) do
      User.create!({
        email: 'test@test.com',
        password: 'password',
        username: 'testtero'
      })
    end

    let!(:card) do
      user.cards.build({
        content: Faker::Lorem.characters(number: 10)
      })
    end

    # before do
    #   user = User.create!({
    #     email: 'test@test.com',
    #     password: 'password',
    #     username: 'testtero'
    #   })
    #   @card = user.cards.build({
    #     content: Faker::Lorem.characters(number: 10)
    #   })
    # end
    
    it '保存ができる' do
      expect(card).to be_valid
    end
```

インスタンス変数は使わない。


## cardモデルで保存できない場合

```
 context 'テキストが空文字の時' do
    let!(:card) do
      user.cards.create({
        content: ""
      })
    end
    
    it '保存ができない' do
      expect(card).to_not be_valid 
    end
  end
```

問題なくテストでOKが出る。

**Comment by tatsuki-okuda** [comment]
# ダミーデータを作る

`gem 'factory_bot_rails'`

 bundleをinstallする

spec>rails_helper.rbに設定を書く。

`config.include FactoryBot::Syntax::Methods`

spec> factories > user.rbでダミーデータを作成する。

```
 factory :user do
    email { Faker::Internet.email }
    password { 'password' }
    username { Faker::JapaneseMedia::StudioGhibli.character }
  end
```

card_spec.rb

`let!(:user) { create(:user)}`

これでテストを実行してみるとうまくいったのでOK!


## cardのダミーデータ作成

userを作ったのでcardも作る。

FactoryBot.define do
  factory :card do
    content {Faker::Lorem.characters(number: 10)}

    imgs { Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec/fixtures/test.png'))}
  end
end

imgsは以下を参考に実装。

[FactoryBotを使った画像ファイルのアップロードテストについて](https://beryus.hatenablog.com/entry/2020/10/03/202230)

card_spec.rb

```
context 'テキストが入力されていたら' do
    let!(:card) { build(:card, user: user) }
    
    it '保存ができる' do
      expect(card).to be_valid
    end
  end

```

これでテストを通すとどうなるのかをみると、
うまくテストが通っている。

他のcardのテストも同様にしてテストが通るかを確認する。
contentが空文字だったりするので、値を指定して書き換えてあげる。

空文字のとき
```
context 'テキストが空文字の時' do
    let!(:card) { build(:card, content: "", user: user) }
    
    it '保存ができない' do
      expect(card).to_not be_valid 
    end
  end
```

1文字の時
 ```
 context 'テキスト1文字' do
    let!(:card) { build(:card, content: Faker::Lorem.characters(number: 1), user: user) }
    
    it '保存ができない' do
      expect(card).to_not be_valid 
    end
  end
```

テストはうまく通っているのでOK!

**Comment by tatsuki-okuda** [comment]
##  リクエストテスト

まずはファイルを作成する

`rails g rspec:request card  `


必要なデータを用意する。

```
let!(:user) { create(:user) }
  let!(:cards) { create_list(:card, 3, user: user) }
```

また、インデックスの保存などはログインしてないと使えないので、
Deviseのメソッドを使えるようにrails_helper.rbに設定を書く。

`config.include Devise::Test::IntegrationHelpers, type: :request`


これでdeviseのメソッドでログインユーザーを作れる。

### ログインしている時の一覧を取得

```
 describe 'GET /cards' do
    context 'ログインしている場合' do
      before do
        sign_in user
      end

      it 'ステータス200が返ってくる' do
        get cards_path
        expect(response).to have_http_status(200)
      end
    end
  end
```

これで実行するとエラーなく、OK!

### 投稿が保存できるか

次に投稿が保存できるかどうかをみる。
postにメソッドを変更する。
createでsaveした時にコントローラでroot_pathにredirectしているので、
ステータスが200ではなくて302になる。

```
describe 'POST /cards' do
    context 'ログインしている場合' do
      before do
        sign_in user
      end

      it '投稿が保存される' do
        card_params = attributes_for(:card)
        # puts card_params
        post cards_path({card: card_params})
        expect(response).to have_http_status(302)
        expect(Card.last.content).to eq(card_params[:content])
        # expect(Card.last.imgs).to eq(card_params[:imgs])
      end
    end
  end
```

画像データに関しては不具合があるので、一旦置いておく、

これでテストをしてみると通ったのでOK！


### ログインしていない時

```
context 'ログインしていない場合' do
      it 'ログイン画面に遷移' do
        card_params = attributes_for(:card)
        post cards_path({card: card_params})
        expect(response).to redirect_to(new_user_session_path)
      end
    end
```

ログインしていない時はdeviseのログインページに飛ぶのが正解、
これでテストを通す。

```
 1) Cards POST /cards ログインしていない場合 保存されない
     Failure/Error: expect(response).to redirect_to(new_user_session_path)
       Expected response to be a <3XX: redirect>, but was a <500: Internal Server Error>
     # ./spec/requests/cards_spec.rb:41:in `block (4 levels) in <top (required)>'

```
https://gist.github.com/tatsuki-okuda/927703cfac31bf36bd8116771800925f


サーバーエラーが起きている。
対象の箇所はredirect_toの部分なので、おそらく、
コントローラーで、ログイン状態でないと機能が使えない設定になっていないのでは
ないかと考えられる。

card_controllerを見てみると、
desivseのメソッドが書かれていなかったので、追加する。

`before_action :authenticate_user!, only: [:index, :shoe, :new, :create,]`

これで再度テストを通すとうまくいった。

**Comment by tatsuki-okuda** [comment]
## apiのテスト

resuestsのファイルの中でapiファイルを作って管理する。

`rails g rspec:request api/comment   `

factoriesでcommentのダミーデータを作る。

comments.rbを作って、以下を記述

```
FactoryBot.define do
  factory :comment do
    content {Faker::Lorem.characters(number: 10)}
  end
end
```


次にcomments_spec.rbファイルを作成して
テストを記載する。

```
  let!(:user) { create(:user)}
  let!(:card) { create(:card, user: user) }
  let!(:comment) { create_list(:comment, 3, card: card) }
```

必要なデータを用意する。

### コメントを取得できるか

コメントを取得して200ステータスが返ってくるかを確認する、

```
describe 'GET /api/comments' do
    it 'status 200' do
      get json_card_comments_path(card_id: card.id)
      expect(response).to have_http_status(200)
    end
  end
```

エラー
 ```
    Failure/Error: let!(:comment) { create_list(:comment, 3, card: card) }
     
     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: Userを入力してください
     # ./spec/requests/api/comments_spec.rb:6:in `block (2 levels) in <top (required)>'
```

https://gist.github.com/tatsuki-okuda/661c834481cb29434883c1fb210176ef

commentにuser情報が悲痛なので、userを入れる。

```
  let!(:user) { create(:user)}
  let!(:card) { create(:card, user: user) }
  let!(:comment) { create_list(:comment, 3, card: card, user: user) }
```

これでもう一回テストをすると

```

) Api::Comments GET /api/comments status 200
     Failure/Error: expect(response).to have_http_status(200)
       expected the response to have status code 200 but it was 500
```

https://gist.github.com/tatsuki-okuda/31ef59653c6a4d9dbb53c2f896cda188


またしてもサーバーエラー発生。

**Comment by tatsuki-okuda** [comment]
## Systemのテスト

`brew cask install chromedriver`

でchromを操作するものを入れておく。

specにsystemのファイルを作成して、
中にcard_spec.rbを作成する。

gemのcapibaraのメソッドを使ってブラウザは操作していく。
https://github.com/teamcapybara/capybara



### rootで入った時に記事を取得できる。

rootで入ったときはフォローしているユーザーの投稿で
いいねが多い順番を新い順番で並べている。

まずはユーザーを二つ作ってフォローしている関係を作る必要がある。

systemのファイルをspec内に作って、card_spec.rbを作成する。


メインのユーザーとfollowingsでユーザーを作る。
あとは投稿が必要なので、投稿も作成する。

```
let!(:user) { create(:user)}
  let!(:followings) { create(:user)}
  let!(:cards) { create_list(:card, 3, user: followings) }
```

rootで投稿が観れるのはログインしている時なので、
describrでログインしている状態を作る。

```
describe 'ログインしている場合' do
    before do
      sign_in user
    end
 end
```

そしてフォローしている状態も追加する。

```
before do
      sign_in user
      user.follow!(followings)
    end
```

投稿はユーザーがフォローしているユーザーの投稿が表示される

```
    it 'フォローしているユーザーの投稿一覧を表示' do
      visit root_path
      cards.each do |card|
        expect(page).to have_content(card.content)
      end
    end
```


ここから投稿にいいねを作って、その記事を取得するようにする。


```
 before do
      sign_in user
      user.follow!(followings)

      cards.each do |card|
        card.likes.create!(user_id: user.id)
      end
    end
```

これでテストを通してみるとうまくいった。


一旦リファクタリングをする


```
describe 'ログインしている場合' do
    before do
      sign_in user
    end

    context 'フォローしている時' do
      before do
        user.follow!(followings)
      end

      context 'いいねしている時' do
        before do
          cards.each do |card|
            card.likes.create!(user_id: user.id)
          end
        end

        it 'フォローしているユーザーの投稿一覧を表示' do
          visit root_path
        
          cards.each do |card|
            expect(page).to have_content(card.content)
          end
        end
      end
    end
  end
```

テストもしっかり通る！！


そして、ログインしていない時と、フォローしていない時、
フォローしているけれどもいいねがない時のテストも行う。


```
context 'ログインしていない場合' do
      it 'ログイン画面に遷移' do
        get root_path
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    context 'ログインしている時' do
      before do
        sign_in user
      end

      context 'ユーザーをフォローしている時' do
        before do
          user.follow!(followings)
        end
  
        context 'いいねしている時' do
          before do
            cards.each do |card|
              card.likes.create!(user_id: user.id)
            end
          end
  
          it 'いいねがついている投稿を表示する' do
            visit root_path
            cards.each do |card|
              expect(page).to have_content(card.content)
            end
          end
        end

        context 'いいねがない時' do
          it '記事がない' do
            visit root_path
            expect(page).to have_content(nil)
          end
        end
      end

      context 'フォローしていない時' do
        it '記事がない' do
          visit root_path
          expect(page).to have_content(nil)
        end
      end
    end
  end
```

問題なくテストが通った！！！


cssを指定してテキストがちゃんと表示されているのかを確認する。

```
it 'いいねがついている投稿を表示する' do
      visit root_path
            cards.each do |card|
             expect(page).to have_content(card.content)
             expect(page).to have_css('.text_first',text: card.content)
             expect(page).to have_content(card.user.username)
             expect(page).to have_css('.user_name', text: card.user.username)
       end
end
```

問題なくテストが通る！！

**Comment by tatsuki-okuda** [comment]
git
https://github.com/tatsuki-okuda/Rails-insta_clone_app/commit/784d4bc1e35e95f887fe2a244bdf46e668633e9b
